name: Backend CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build application
        run: mvn -B -U -Dmaven.repo.local=/tmp/m2 clean package
        
      - name: Build container image
        run: |
          docker build -t backend-ci-cd:${{ github.sha }} .

      - name: Run app in DEV environment
        run: |
          SPRING_PROFILES_ACTIVE=dev java -jar target/*.jar &
          sleep 10
          curl http://localhost:8080/health

      - name: Run app in TEST environment
        run: |
          SPRING_PROFILES_ACTIVE=test java -jar target/*.jar &
          sleep 10
          curl http://localhost:8080/health

      - name: Run app in PROD environment
        run: |
          SPRING_PROFILES_ACTIVE=prod java -jar target/*.jar &
          sleep 10
          curl http://localhost:8080/health
